[project]
name = "taller"
version = "0.1.0"
description = "Taller de Programacion - UNTDF"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
]
